"""
OrthoBraceForge — FormaAI Agent
Wraps andreyka/forma-ai-service (build123d self-correction).
"""
import logging
import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

from config import (
    AFO_HEIGHT_MAX_MM,
    AFO_HEIGHT_MIN_MM,
    AFO_LENGTH_MAX_MM,
    AFO_LENGTH_MIN_MM,
    BUILD123D_TIMEOUT_SEC,
    EXPORT_DIR,
    MAX_AGENT_ITERATIONS,
)
from exceptions import CADGenerationError

from .base import AgentResult, BaseAgent

logger = logging.getLogger("orthobraceforge.agents")


class FormaAIAgent(BaseAgent):
    """
    Wraps forma-ai-service for build123d CAD generation with
    control-flow self-correction. PREFERRED engine for AFO generation.
    Generates Python build123d code, executes it, validates geometry,
    and iteratively corrects based on error feedback.
    """

    def __init__(self):
        super().__init__("forma_ai")

    def execute(self, params: Dict[str, Any]) -> AgentResult:
        self._trace = []
        self._log("Starting build123d self-correction loop")

        constraints = params.get("constraints", {})
        max_iter = params.get("max_iterations", MAX_AGENT_ITERATIONS)
        design_id = params.get("design_id", "temp")

        output_stl = str(EXPORT_DIR / f"forma_{design_id}.stl")
        output_step = str(EXPORT_DIR / f"forma_{design_id}.step")
        output_py = str(EXPORT_DIR / f"forma_{design_id}_build123d.py")

        errors: List[str] = []
        b123d_code = None

        for iteration in range(1, max_iter + 1):
            self._log(f"Iteration {iteration}/{max_iter}")

            try:
                # Generate build123d Python code
                b123d_code = self._generate_build123d(constraints, b123d_code, errors, output_stl, output_step)
                self._log(f"Generated build123d code ({len(b123d_code)} chars)")

                # Write and execute
                Path(output_py).write_text(b123d_code, encoding="utf-8")

                exec_result = self._execute_build123d(output_py, output_stl, output_step)

                if exec_result["success"]:
                    # Validate geometry
                    validation = self._validate_geometry(output_stl, constraints)
                    if validation["valid"]:
                        self._log("Geometry validated successfully")
                        return AgentResult(
                            success=True,
                            agent_name=self.name,
                            output_data={
                                "build123d_code": b123d_code,
                                "validation": validation,
                            },
                            output_files=[output_stl, output_step, output_py],
                            iterations_used=iteration,
                            trace_log=list(self._trace),
                        )
                    else:
                        errors = validation.get("errors", ["Geometry validation failed"])
                        self._log(f"Validation failed: {errors}")
                else:
                    errors = exec_result.get("errors", ["Execution failed"])
                    self._log(f"Execution failed: {errors}")

            except (CADGenerationError, subprocess.SubprocessError, OSError) as e:
                errors = [str(e)]
                self._log(f"CAD error: {e}")
            except Exception as e:
                logger.error(f"[{self.name}] Unexpected error in iteration {iteration}: {e}", exc_info=True)
                errors = [str(e)]

        return AgentResult(
            success=False,
            agent_name=self.name,
            errors=[f"Failed after {max_iter} iterations"] + errors,
            iterations_used=max_iter,
            trace_log=list(self._trace),
        )

    def _generate_build123d(self, constraints: Dict, previous_code: Optional[str],
                             errors: List[str], stl_path: str = "", step_path: str = "") -> str:
        """
        Generate build123d Python code for AFO.
        In production: local LLM generates code; here returns parametric template.
        """
        foot_length = constraints.get("foot_length_mm", 180)
        ankle_width = constraints.get("ankle_width_mm", 50)
        thickness = constraints.get("wall_thickness_mm", 3.0)
        ankle_angle = constraints.get("ankle_target_deg", 0)
        afo_type = constraints.get("afo_type", "solid")
        growth = constraints.get("growth_accommodation_mm", 5)

        return f'''"""
OrthoBraceForge — build123d Parametric Pediatric AFO
Auto-generated by FormaAI agent with self-correction
"""
from build123d import (
    BuildPart, BuildSketch, BuildLine, Compound, Plane, Axis, Mode,
    Line, Spline, RadiusArc, Circle, Sphere,
    Locations, make_face, extrude, rotate,
)
import math

# === Patient-Specific Parameters ===
FOOT_LENGTH = {foot_length} + {growth}  # mm (includes growth margin)
FOOT_WIDTH = {ankle_width * 1.4:.1f}     # mm (estimated from ankle width)
ANKLE_WIDTH = {ankle_width}              # mm
WALL_THICKNESS = {thickness}             # mm
ANKLE_ANGLE_DEG = {ankle_angle}          # degrees dorsiflexion
AFO_TYPE = "{afo_type}"
CALF_HEIGHT = 180                        # mm (ankle to fibular head - 15mm)
CALF_CIRC = ANKLE_WIDTH * math.pi * 1.2  # mm estimated

# === Footplate ===
with BuildPart() as footplate:
    with BuildSketch():
        # Anatomical footplate shape
        with BuildLine():
            # Heel
            l1 = Line((0, 0), (0, FOOT_WIDTH))
            # Lateral border
            l2 = Spline((0, FOOT_WIDTH),
                        (FOOT_LENGTH * 0.3, FOOT_WIDTH * 1.05),
                        (FOOT_LENGTH * 0.7, FOOT_WIDTH * 0.95),
                        (FOOT_LENGTH, FOOT_WIDTH * 0.5))
            # Toe
            l3 = RadiusArc((FOOT_LENGTH, FOOT_WIDTH * 0.5),
                           (FOOT_LENGTH, 0), -FOOT_WIDTH * 0.3)
            # Medial border
            l4 = Spline((FOOT_LENGTH, 0),
                        (FOOT_LENGTH * 0.7, -FOOT_WIDTH * 0.05),
                        (FOOT_LENGTH * 0.3, 0),
                        (0, 0))
        make_face()
    extrude(amount=WALL_THICKNESS)

# === Posterior Wall ===
with BuildPart() as posterior_wall:
    with BuildSketch(Plane.XZ.offset(-FOOT_WIDTH / 2)):
        # Posterior wall profile
        with BuildLine():
            l1 = Line((0, WALL_THICKNESS), (0, CALF_HEIGHT))
            l2 = Line((0, CALF_HEIGHT), (WALL_THICKNESS, CALF_HEIGHT))
            l3 = Line((WALL_THICKNESS, CALF_HEIGHT), (WALL_THICKNESS, WALL_THICKNESS))
            l4 = Line((WALL_THICKNESS, WALL_THICKNESS), (0, WALL_THICKNESS))
        make_face()
    extrude(amount=ANKLE_WIDTH + 2 * WALL_THICKNESS)

    # Ankle angle rotation
    if ANKLE_ANGLE_DEG != 0:
        rotate(axis=Axis.Y, angle=ANKLE_ANGLE_DEG)

    # Malleolar relief cutouts
    with BuildPart(mode=Mode.SUBTRACT):
        with Locations([(WALL_THICKNESS/2, -ANKLE_WIDTH/2, ANKLE_WIDTH * 0.6),
                        (WALL_THICKNESS/2, ANKLE_WIDTH/2, ANKLE_WIDTH * 0.6)]):
            Sphere(radius=8)  # 8mm relief for malleoli

# === Calf Cuff (partial cylinder) ===
with BuildPart() as calf_cuff:
    calf_radius = CALF_CIRC / (2 * math.pi)
    with BuildSketch(Plane.XY.offset(CALF_HEIGHT * 0.65)):
        Circle(calf_radius + WALL_THICKNESS)
        Circle(calf_radius, mode=Mode.SUBTRACT)
        # Opening for donning (anterior 120°)
        with BuildLine():
            l1 = Line((-calf_radius * 1.5, 0), (calf_radius * 1.5, 0))
            l2 = Line((calf_radius * 1.5, 0), (calf_radius * 1.5, calf_radius * 1.5))
            l3 = Line((calf_radius * 1.5, calf_radius * 1.5),
                      (-calf_radius * 1.5, calf_radius * 1.5))
            l4 = Line((-calf_radius * 1.5, calf_radius * 1.5), (-calf_radius * 1.5, 0))
        make_face(mode=Mode.SUBTRACT)
    extrude(amount=CALF_HEIGHT * 0.3)

# === Assembly ===
afo_assembly = Compound(children=[
    footplate.part,
    posterior_wall.part,
    calf_cuff.part,
])

# === Export ===
afo_assembly.export_stl("{stl_path}")
afo_assembly.export_step("{step_path}")
print("BUILD123D_SUCCESS: AFO exported to STL and STEP")
'''

    def _execute_build123d(self, py_path: str, stl_path: str,
                            step_path: str) -> Dict:
        """Execute build123d script as subprocess."""
        try:
            result = subprocess.run(
                ["python", py_path],
                capture_output=True, text=True, timeout=BUILD123D_TIMEOUT_SEC,
                env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
            )
            success = (
                result.returncode == 0
                and "BUILD123D_SUCCESS" in result.stdout
                and Path(stl_path).exists()
            )
            return {
                "success": success,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "errors": [result.stderr] if not success else [],
            }
        except subprocess.TimeoutExpired:
            return {"success": False, "errors": ["Build123d execution timed out (180s)"]}
        except OSError as e:
            return {"success": False, "errors": [str(e)]}

    def _validate_geometry(self, stl_path: str, constraints: Dict) -> Dict:
        """Validate STL geometry against design constraints."""
        try:
            import trimesh
            mesh = trimesh.load(stl_path)

            errors = []
            bounds = mesh.bounds  # [[min_x, min_y, min_z], [max_x, max_y, max_z]]
            dims = bounds[1] - bounds[0]

            # Check overall dimensions are reasonable for an AFO
            if dims[0] < AFO_LENGTH_MIN_MM or dims[0] > AFO_LENGTH_MAX_MM:
                errors.append(f"Length {dims[0]:.1f}mm outside AFO range [{AFO_LENGTH_MIN_MM}-{AFO_LENGTH_MAX_MM}]")
            if dims[2] < AFO_HEIGHT_MIN_MM or dims[2] > AFO_HEIGHT_MAX_MM:
                errors.append(f"Height {dims[2]:.1f}mm outside AFO range [{AFO_HEIGHT_MIN_MM}-{AFO_HEIGHT_MAX_MM}]")
            if not mesh.is_watertight:
                errors.append("Mesh is not watertight — not printable")

            return {
                "valid": len(errors) == 0,
                "dimensions_mm": dims.tolist(),
                "volume_cm3": mesh.volume / 1000,
                "is_watertight": mesh.is_watertight,
                "triangle_count": len(mesh.faces),
                "errors": errors,
            }
        except ImportError:
            return {"valid": True, "errors": [], "note": "trimesh not available for validation"}
        except (OSError, ValueError) as e:
            return {"valid": False, "errors": [str(e)]}
